== awar - deploying a war in OpenShift
Demonstrates how to expose a war file in OpenShift using EAP.

.Setup
After cloining the project run the following commands from its root directory

.Login and create a new project
----
$ oc login ...
$ oc new-project war-apps
---- 
.Create the `jboss-eap70-openshift` image stream in your project
----
$ oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap70-image-stream.json
----
.Create a new EAP app based on the current directory containing the war and name it awar
----
$ oc new-app jboss-eap70-openshift:1.7~. --name awar
----
.Exposed the service for the new app
----
$ oc expose svc/awar
----
.Display your routes
----
$ oc get routes
NAME      HOST/PORT                                        PATH      SERVICES   PORT       TERMINATION   WILDCARD
awar      awar-war-apps.apps.rhpds.openshift.opentlc.com             awar       8080-tcp                 None
----

.Open the application in a browser
Copy the HOST/PORT address above and suffix it with  `/sample` (the war files name).
paste this in your browser.  The example above becomes `http://awar-war-apps.apps.rhpds.openshift.opentlc.com/sample`

== Additional info

.Verify image stream
----
oc describe is jboss-eap70-openshift
----
The results will include all the version/tags and where the `1.7` in `jboss-eap70-openshift:1.7~. --name awar` was derived from

.Listing the projects image streams
----
oc get is
----

.Deploying from git
----
oc new-app jboss-eap70-openshift:1.7~https://github.com/craigivy/awar --name mysample
----

.Credit
This project is based on https://blog.openshift.com/deploying-war-file-openshift-online-3/[Deploying a WAR File to OpenShift Online Next Gen]